### ISSUE TITLE
I get a read error and can't find a fix

### ISSUE THREAD

**Issue by saboteur13** [Capps0611/DayZ-Player-Leaderboard-Bot#3]
Hi Capps

After my last post on the other issue you have Closed, I managed to get the Discord bot working with your code.

I had to use `npm i nodemon` in stead of `npm i` to build the packages.

The issue that I am having now is after the bot is started and in Discord when I type !leaderboard in the chat, I get the following error showing up in the node.js command prompt:

Arguments:
Error: read ECONNRESET (data socket)
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Then the discord bot replies in the chat with a leaderboard, but with no data.

I assume this is some kind of reading issue, but all my files and folders are shared with "Everyone".

I have a few player .json files in the Leaderboard folder in my profile folder.

Hope you can help?

**Comment by Capps0611** [comment]
Can you send me a player json file that you have. Could you also send me your settings.json file (remove any sensitive information such as bot token or FTP info)

**Comment by saboteur13** [comment]
Hi. Thanks for the response.

I really don't want to bother you with nonsense, but please excuse I am still noob with JS.

I actually got past that point (don't ask how). The bot starts and sees !leaderboard command from Discord, but now it gives a FTP login failure error in JS cmd::

Command received: leaderboard
Arguments:
FTPError: 530 User cannot log in.
    at FTPContext._onControlSocketData (C:\Servers\DayZ Deathmatch\DayZ\Profiles\Leaderboard\DayZ-Player-Leaderboard-Bot-master\node_modules\basic-ftp\dist\FtpContext.js:282:39)
    at Socket.<anonymous> (C:\Servers\DayZ Deathmatch\DayZ\Profiles\Leaderboard\DayZ-Player-Leaderboard-Bot-master\node_modules\basic-ftp\dist\FtpContext.js:123:44)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:278:11)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 530
}

My FTP details are correct and file sharing also. I have tried many things to no success. I can access my FTP from anywhere and have full access.

I know its not ideal to add the files to the FTP directory, but I tried everything. That will be moved if it works.

Here are those attachments...not sure if it will be of much help.
[DC.zip](https://github.com/Capps0611/DayZ-Player-Leaderboard-Bot/files/5347376/DC.zip)

Feel free to make a time if you want to have a chat or look yourself remotely

**Comment by saboteur13** [comment]
I managed to get it to work.

Was an issue with port forwarding. Just by forwarding the FTP port (e.g. 21) didn't work, but when I forwarded a port range around the FTP port (e.g. 20-25) then it worked.

Thanks again
