### ISSUE TITLE
erreur 

### ISSUE THREAD

**Issue by rfrost9912** [Capps0611/DayZ-Player-Leaderboard-Bot#5]
when start npm start have issue whith package.json

C:\Users\reg_f\leadeer>npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\reg_f\leadeer\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\reg_f\leadeer\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\reg_f\AppData\Roaming\npm-cache\_logs\2021-02-10T14_12_43_344Z-debug.log

my discord is R_frost#1522 you cant mp for help me out thank
your help is appreciate

**Comment by Capps0611** [comment]
It looks like the package.json file is missing from the leader folder. Make sure you extract all contents from the download zip file into the same directory!

**Comment by rfrost9912** [comment]
All the files its on the same file, everything its extract and the package.json is there.

Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.

________________________________

**Comment by krussedull** [comment]
same problem here, was this fixed?

**Comment by Capps0611** [comment]
Are you still getting this error? And did you run npm i before npm start?

**Comment by rfrost9912** [comment]
still have error and i did npm i before start

**Comment by rfrost9912** [comment]
i found the issue for the file but now have that one after make npm i and npm start.
C:\Users\reg_f\leader\DayZ-Player-Leaderboard-Bot-master>npm i
npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN dayz_player_leaderboard_bot@1.0.0 No repository field.

audited 10 packages in 0.685s
found 0 vulnerabilities

**Comment by krussedull** [comment]
Run this -> npm install -g nodemon . let me know if you get all working , im struggeling aswell whit this one , Krussedull86#1183 you find me at : discord.gg/hfYgUukNUf

**Comment by rfrost9912** [comment]
I would love it to work because its very interesting as a leaderboard but its not working, maybe I who made a mistake. but if you want to help me know her would be very appreciated. The project is to rate in the meantime. my discord  R_frost#1522

code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\reg_f\\leader\\DayZ-Player-Leaderboard-Bot-master\\dayzPlayerLeaderboardBot.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
