### ISSUE TITLE
help pleace?

### ISSUE THREAD

**Issue by krussedull** [Capps0611/DayZ-Player-Leaderboard-Bot#7]
C:\Discordbot>npm run
Lifecycle scripts included in dayz_player_leaderboard_bot:
  start
    nodemon --ignore "playerJsons/" dayzPlayerLeaderboardBot.js

C:\Discordbot>npm start

> dayz_player_leaderboard_bot@1.0.0 start C:\Discordbot
> nodemon --ignore "playerJsons/" dayzPlayerLeaderboardBot.js

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dayz_player_leaderboard_bot@1.0.0 start: `nodemon --ignore "playerJsons/" dayzPlayerLeaderboardBot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dayz_player_leaderboard_bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\napst\AppData\Roaming\npm-cache\_logs\2021-02-11T13_16_50_013Z-debug.log

C:\Discordbot>

**Comment by Capps0611** [comment]
Run this -> **npm install -g nodemon**

**Comment by krussedull** [comment]
Will try

**Comment by krussedull** [comment]
now it pulls the files as it shoude, but do not write in discord channel

**Comment by krussedull** [comment]
Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. Med enerett.

C:\WINDOWS\system32>cd..

C:\Windows>cd..

C:\>cd discordbot

C:\Discordbot>npm i
npm WARN dayz_player_leaderboard_bot@1.0.0 No repository field.

audited 64 packages in 0.594s
found 0 vulnerabilities


C:\Discordbot>npm install -g nodemon
C:\Users\napst\AppData\Roaming\npm\nodemon -> C:\Users\napst\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js

> nodemon@2.0.7 postinstall C:\Users\napst\AppData\Roaming\npm\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\nodemon\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ nodemon@2.0.7
updated 1 package in 3.671s

C:\Discordbot>
C:\Discordbot>
C:\Discordbot>npm i
npm WARN dayz_player_leaderboard_bot@1.0.0 No repository field.

audited 64 packages in 0.596s
found 0 vulnerabilities


C:\Discordbot>npm start

> dayz_player_leaderboard_bot@1.0.0 start C:\Discordbot
> nodemon --ignore "playerJsons/" dayzPlayerLeaderboardBot.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dayzPlayerLeaderboardBot.js`
Connected as DayzEndStats#4962
Command received: leaderboard
Arguments:
FTPError: 550 -a /194.147.121.125_2424/SC/Leaderboard/: failed
    at FTPContext._onControlSocketData (C:\Discordbot\node_modules\basic-ftp\dist\FtpContext.js:282:39)
    at Socket.<anonymous> (C:\Discordbot\node_modules\basic-ftp\dist\FtpContext.js:123:44)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:280:11)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 550
}
Command received: leaderboard
Arguments:
FTPError: 550 -a /194.147.121.125_2424/SC/Leaderboard/: failed
    at FTPContext._onControlSocketData (C:\Discordbot\node_modules\basic-ftp\dist\FtpContext.js:282:39)
    at Socket.<anonymous> (C:\Discordbot\node_modules\basic-ftp\dist\FtpContext.js:123:44)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:280:11)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 550
}

**Comment by krussedull** [comment]
rs
[nodemon] starting `node dayzPlayerLeaderboardBot.js`
Connected as DayzEndStats#4962
Command received: leaderboard
Arguments:
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read

**Comment by krussedull** [comment]
but it downlads all files whjit content now

**Comment by krussedull** [comment]
no help to get?
